# Generated by Django 2.1.7 on 2019-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tc_id',
            field=models.IntegerField(unique=True),
        ),
    ]
