# Generated by Django 2.1.7 on 2019-04-08 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190407_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='survey',
            name='surveyors',
        ),
        migrations.AddField(
            model_name='survey',
            name='surveyors',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='main.Surveyer'),
        ),
    ]
