# Generated by Django 2.1.7 on 2019-04-13 13:00

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main', '0004_auto_20190408_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Surveyer',
            new_name='Surveyor',
        ),
    ]
