# Generated by Django 2.1.7 on 2019-04-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190414_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='related_to',
            new_name='releated_to',
        ),
    ]
